### PR TITLE
Fix duplicate bindings

### PR DESCRIPTION
**Pull request by amanusk**
Ignore duplicate bindings of bindgen
Fix for #17

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
this pr should be merged asap, for the convenience of testing  @omershlo

**Comment by omershlo** [comment]
Did you checked that it is not effecting the mac os build by any chance?

**Comment by HAOYUatHZ** [comment]
i don't have mac machine

but it works fine on
ubuntu 17.04     x64
rustc 1.35.0 (3c235d560 2019-05-20)
rustup 1.18.3 (435397f48 2019-05-22)
cargo 1.35.0 (6f3e9c367 2019-04-04)

**Comment by amanusk** [comment]
Tried building on a MacOS, didn't experience any breaking behaviour.

**Pull request merged**
